version: '3'
services:
  connector-virustotal:
    image: opencti/connector-template:5.2.4
    environment:
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_TYPE=INTERNAL_ENRICHMENT
      - CONNECTOR_NAME=Template
      - CONNECTOR_SCOPE=StixFile,Artifact
      - CONNECTOR_AUTO=true # Enable/disable auto-enrichment of observables
      - CONNECTOR_CONFIDENCE_LEVEL=50 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - TEMPLATE_SERVICE_VARIABLE_1=ChangeMeNumber1
      - TEMPLATE_SERVICE_VARIABLE_2=ChangeMeNumber2
    restart: always
